package com.mobica.cloud.aws.db;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import static com.mobica.cloud.aws.db.Message.TABLE_NAME;

@DynamoDBTable(tableName = TABLE_NAME)
public class Message {
    public static final String TABLE_NAME = "opendoors17-dev-test";
    public static final String ID_NAME = "_id";
    public static final String MESSAGE_NAME = "message";

    @DynamoDBHashKey(attributeName = ID_NAME)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = MESSAGE_NAME)
    private String message;

    public Message(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Message{" +
                "id=" + id +
                ", message='" + message + '\'' +
                '}';
    }
}
